//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligentFactory.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string STATIONNUMBER {
            get {
                return ((string)(this["STATIONNUMBER"]));
            }
            set {
                this["STATIONNUMBER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string NETWORKNUMBER {
            get {
                return ((string)(this["NETWORKNUMBER"]));
            }
            set {
                this["NETWORKNUMBER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string GROUPNUMBER {
            get {
                return ((string)(this["GROUPNUMBER"]));
            }
            set {
                this["GROUPNUMBER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public string CCLINK_MODE {
            get {
                return ((string)(this["CCLINK_MODE"]));
            }
            set {
                this["CCLINK_MODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B2800")]
        public string INPUT_ALIVE {
            get {
                return ((string)(this["INPUT_ALIVE"]));
            }
            set {
                this["INPUT_ALIVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B2802")]
        public string INPUT_EMERGENCY_STOP {
            get {
                return ((string)(this["INPUT_EMERGENCY_STOP"]));
            }
            set {
                this["INPUT_EMERGENCY_STOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B2803")]
        public string INPUT_DOOR_OPEN {
            get {
                return ((string)(this["INPUT_DOOR_OPEN"]));
            }
            set {
                this["INPUT_DOOR_OPEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B2804")]
        public string INPUT_PLC_ALARM {
            get {
                return ((string)(this["INPUT_PLC_ALARM"]));
            }
            set {
                this["INPUT_PLC_ALARM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B2805")]
        public string INPUT_PLC_WARNING {
            get {
                return ((string)(this["INPUT_PLC_WARNING"]));
            }
            set {
                this["INPUT_PLC_WARNING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B280A")]
        public string INPUT_PC_ALARM_ACK {
            get {
                return ((string)(this["INPUT_PC_ALARM_ACK"]));
            }
            set {
                this["INPUT_PC_ALARM_ACK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B280B")]
        public string INPUT_PC_WARNING_ACK {
            get {
                return ((string)(this["INPUT_PC_WARNING_ACK"]));
            }
            set {
                this["INPUT_PC_WARNING_ACK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B2820")]
        public string INPUT_DRYRUN {
            get {
                return ((string)(this["INPUT_DRYRUN"]));
            }
            set {
                this["INPUT_DRYRUN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B2821")]
        public string INPUT_PC_NOT_USE {
            get {
                return ((string)(this["INPUT_PC_NOT_USE"]));
            }
            set {
                this["INPUT_PC_NOT_USE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B2900")]
        public string INPUT_REQ_ALIGN_LAMI {
            get {
                return ((string)(this["INPUT_REQ_ALIGN_LAMI"]));
            }
            set {
                this["INPUT_REQ_ALIGN_LAMI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B2901")]
        public string INPUT_ACK_ALIGN_LAMI {
            get {
                return ((string)(this["INPUT_ACK_ALIGN_LAMI"]));
            }
            set {
                this["INPUT_ACK_ALIGN_LAMI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B290A")]
        public string INPUT_REQ_ALIGN_LAMI_CAL {
            get {
                return ((string)(this["INPUT_REQ_ALIGN_LAMI_CAL"]));
            }
            set {
                this["INPUT_REQ_ALIGN_LAMI_CAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B290B")]
        public string INPUT_ACK_ALIGN_LAMI_CAL_MOVE {
            get {
                return ((string)(this["INPUT_ACK_ALIGN_LAMI_CAL_MOVE"]));
            }
            set {
                this["INPUT_ACK_ALIGN_LAMI_CAL_MOVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B2910")]
        public string INPUT_REQ_ALIGN_SUPPLY {
            get {
                return ((string)(this["INPUT_REQ_ALIGN_SUPPLY"]));
            }
            set {
                this["INPUT_REQ_ALIGN_SUPPLY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B2911")]
        public string INPUT_ACK_ALIGN_SUPPLY {
            get {
                return ((string)(this["INPUT_ACK_ALIGN_SUPPLY"]));
            }
            set {
                this["INPUT_ACK_ALIGN_SUPPLY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B291A")]
        public string INPUT_REQ_ALIGN_SUPPLY_CAL {
            get {
                return ((string)(this["INPUT_REQ_ALIGN_SUPPLY_CAL"]));
            }
            set {
                this["INPUT_REQ_ALIGN_SUPPLY_CAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B291B")]
        public string INPUT_ACK_ALIGN_SUPPLY_CAL_MOVE {
            get {
                return ((string)(this["INPUT_ACK_ALIGN_SUPPLY_CAL_MOVE"]));
            }
            set {
                this["INPUT_ACK_ALIGN_SUPPLY_CAL_MOVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W2804")]
        public string INPUT_PLC_ALARM_CODE {
            get {
                return ((string)(this["INPUT_PLC_ALARM_CODE"]));
            }
            set {
                this["INPUT_PLC_ALARM_CODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W2805")]
        public string INPUT_PLC_WARNING_CODE {
            get {
                return ((string)(this["INPUT_PLC_WARNING_CODE"]));
            }
            set {
                this["INPUT_PLC_WARNING_CODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W2810")]
        public string INPUT_MODEL_NO {
            get {
                return ((string)(this["INPUT_MODEL_NO"]));
            }
            set {
                this["INPUT_MODEL_NO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W2811")]
        public string INPUT_MODEL_NAME1 {
            get {
                return ((string)(this["INPUT_MODEL_NAME1"]));
            }
            set {
                this["INPUT_MODEL_NAME1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W2812")]
        public string INPUT_MODEL_NAME2 {
            get {
                return ((string)(this["INPUT_MODEL_NAME2"]));
            }
            set {
                this["INPUT_MODEL_NAME2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W2813")]
        public string INPUT_MODEL_NAME3 {
            get {
                return ((string)(this["INPUT_MODEL_NAME3"]));
            }
            set {
                this["INPUT_MODEL_NAME3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W2814")]
        public string INPUT_MODEL_NAME4 {
            get {
                return ((string)(this["INPUT_MODEL_NAME4"]));
            }
            set {
                this["INPUT_MODEL_NAME4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W2815")]
        public string INPUT_MODEL_NAME5 {
            get {
                return ((string)(this["INPUT_MODEL_NAME5"]));
            }
            set {
                this["INPUT_MODEL_NAME5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W2816")]
        public string INPUT_MODEL_NAME6 {
            get {
                return ((string)(this["INPUT_MODEL_NAME6"]));
            }
            set {
                this["INPUT_MODEL_NAME6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W2817")]
        public string INPUT_MODEL_NAME7 {
            get {
                return ((string)(this["INPUT_MODEL_NAME7"]));
            }
            set {
                this["INPUT_MODEL_NAME7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W2818")]
        public string INPUT_MODEL_NAME8 {
            get {
                return ((string)(this["INPUT_MODEL_NAME8"]));
            }
            set {
                this["INPUT_MODEL_NAME8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W2819")]
        public string INPUT_MODEL_NAME9 {
            get {
                return ((string)(this["INPUT_MODEL_NAME9"]));
            }
            set {
                this["INPUT_MODEL_NAME9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W2820")]
        public string INPUT_MODEL_NAME10 {
            get {
                return ((string)(this["INPUT_MODEL_NAME10"]));
            }
            set {
                this["INPUT_MODEL_NAME10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B5000")]
        public string OUTPUT_ALIVE {
            get {
                return ((string)(this["OUTPUT_ALIVE"]));
            }
            set {
                this["OUTPUT_ALIVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B5004")]
        public string OUTPUT_PLC_ALARM_ACK {
            get {
                return ((string)(this["OUTPUT_PLC_ALARM_ACK"]));
            }
            set {
                this["OUTPUT_PLC_ALARM_ACK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B5005")]
        public string OUTPUT_PLC_WARNING_ACK {
            get {
                return ((string)(this["OUTPUT_PLC_WARNING_ACK"]));
            }
            set {
                this["OUTPUT_PLC_WARNING_ACK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B5006")]
        public string OUTPUT_PC_ALARM {
            get {
                return ((string)(this["OUTPUT_PC_ALARM"]));
            }
            set {
                this["OUTPUT_PC_ALARM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B5007")]
        public string OUTPUT_PC_WARNING {
            get {
                return ((string)(this["OUTPUT_PC_WARNING"]));
            }
            set {
                this["OUTPUT_PC_WARNING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B500A")]
        public string OUTPUT_PC_MODE {
            get {
                return ((string)(this["OUTPUT_PC_MODE"]));
            }
            set {
                this["OUTPUT_PC_MODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B5100")]
        public string OUTPUT_REQ_ALIGN_LAMI_ACK {
            get {
                return ((string)(this["OUTPUT_REQ_ALIGN_LAMI_ACK"]));
            }
            set {
                this["OUTPUT_REQ_ALIGN_LAMI_ACK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B5101")]
        public string OUTPUT_REQ_ALIGN_LAMI_MOVE {
            get {
                return ((string)(this["OUTPUT_REQ_ALIGN_LAMI_MOVE"]));
            }
            set {
                this["OUTPUT_REQ_ALIGN_LAMI_MOVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B510A")]
        public string OUTPUT_REQ_ALIGN_LAMI_CAL_ACK {
            get {
                return ((string)(this["OUTPUT_REQ_ALIGN_LAMI_CAL_ACK"]));
            }
            set {
                this["OUTPUT_REQ_ALIGN_LAMI_CAL_ACK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B510B")]
        public string OUTPUT_REQ_ALIGN_LAMI_MOVE_ACK {
            get {
                return ((string)(this["OUTPUT_REQ_ALIGN_LAMI_MOVE_ACK"]));
            }
            set {
                this["OUTPUT_REQ_ALIGN_LAMI_MOVE_ACK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B5110")]
        public string OUTPUT_REQ_ALIGN_SUPPLY_ACK {
            get {
                return ((string)(this["OUTPUT_REQ_ALIGN_SUPPLY_ACK"]));
            }
            set {
                this["OUTPUT_REQ_ALIGN_SUPPLY_ACK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B5111")]
        public string OUTPUT_REQ_ALIGN_SUPPLY_MOVE {
            get {
                return ((string)(this["OUTPUT_REQ_ALIGN_SUPPLY_MOVE"]));
            }
            set {
                this["OUTPUT_REQ_ALIGN_SUPPLY_MOVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B511A")]
        public string OUTPUT_REQ_ALIGN_SUPPLY_CAL_ACK {
            get {
                return ((string)(this["OUTPUT_REQ_ALIGN_SUPPLY_CAL_ACK"]));
            }
            set {
                this["OUTPUT_REQ_ALIGN_SUPPLY_CAL_ACK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B511B")]
        public string OUTPUT_REQ_ALIGN_SUPPLY_MOVE_ACK {
            get {
                return ((string)(this["OUTPUT_REQ_ALIGN_SUPPLY_MOVE_ACK"]));
            }
            set {
                this["OUTPUT_REQ_ALIGN_SUPPLY_MOVE_ACK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W5006")]
        public string OUTPUT_ALARM_CODE {
            get {
                return ((string)(this["OUTPUT_ALARM_CODE"]));
            }
            set {
                this["OUTPUT_ALARM_CODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W5007")]
        public string OUTPUT_WARNING_CODE {
            get {
                return ((string)(this["OUTPUT_WARNING_CODE"]));
            }
            set {
                this["OUTPUT_WARNING_CODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W5010")]
        public string OUTPUT_MODEL_NO {
            get {
                return ((string)(this["OUTPUT_MODEL_NO"]));
            }
            set {
                this["OUTPUT_MODEL_NO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W5011")]
        public string OUTPUT_MODEL_NAME1 {
            get {
                return ((string)(this["OUTPUT_MODEL_NAME1"]));
            }
            set {
                this["OUTPUT_MODEL_NAME1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W5012")]
        public string OUTPUT_MODEL_NAME2 {
            get {
                return ((string)(this["OUTPUT_MODEL_NAME2"]));
            }
            set {
                this["OUTPUT_MODEL_NAME2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W5013")]
        public string OUTPUT_MODEL_NAME3 {
            get {
                return ((string)(this["OUTPUT_MODEL_NAME3"]));
            }
            set {
                this["OUTPUT_MODEL_NAME3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W5014")]
        public string OUTPUT_MODEL_NAME4 {
            get {
                return ((string)(this["OUTPUT_MODEL_NAME4"]));
            }
            set {
                this["OUTPUT_MODEL_NAME4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W5015")]
        public string OUTPUT_MODEL_NAME5 {
            get {
                return ((string)(this["OUTPUT_MODEL_NAME5"]));
            }
            set {
                this["OUTPUT_MODEL_NAME5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W5016")]
        public string OUTPUT_MODEL_NAME6 {
            get {
                return ((string)(this["OUTPUT_MODEL_NAME6"]));
            }
            set {
                this["OUTPUT_MODEL_NAME6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W5017")]
        public string OUTPUT_MODEL_NAME7 {
            get {
                return ((string)(this["OUTPUT_MODEL_NAME7"]));
            }
            set {
                this["OUTPUT_MODEL_NAME7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W5018")]
        public string OUTPUT_MODEL_NAME8 {
            get {
                return ((string)(this["OUTPUT_MODEL_NAME8"]));
            }
            set {
                this["OUTPUT_MODEL_NAME8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W5019")]
        public string OUTPUT_MODEL_NAME9 {
            get {
                return ((string)(this["OUTPUT_MODEL_NAME9"]));
            }
            set {
                this["OUTPUT_MODEL_NAME9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W5020")]
        public string OUTPUT_MODEL_NAME10 {
            get {
                return ((string)(this["OUTPUT_MODEL_NAME10"]));
            }
            set {
                this["OUTPUT_MODEL_NAME10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W5100")]
        public string OUTPUT_ALIGN_LAMI_X_INC {
            get {
                return ((string)(this["OUTPUT_ALIGN_LAMI_X_INC"]));
            }
            set {
                this["OUTPUT_ALIGN_LAMI_X_INC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W5102")]
        public string OUTPUT_ALIGN_LAMI_Y_INC {
            get {
                return ((string)(this["OUTPUT_ALIGN_LAMI_Y_INC"]));
            }
            set {
                this["OUTPUT_ALIGN_LAMI_Y_INC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W5104")]
        public string OUTPUT_ALIGN_LAMI_T_INC {
            get {
                return ((string)(this["OUTPUT_ALIGN_LAMI_T_INC"]));
            }
            set {
                this["OUTPUT_ALIGN_LAMI_T_INC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W510A")]
        public string OUTPUT_ALIGN_LAMI_X_ABS {
            get {
                return ((string)(this["OUTPUT_ALIGN_LAMI_X_ABS"]));
            }
            set {
                this["OUTPUT_ALIGN_LAMI_X_ABS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W510C")]
        public string OUTPUT_ALIGN_LAMI_Y_ABS {
            get {
                return ((string)(this["OUTPUT_ALIGN_LAMI_Y_ABS"]));
            }
            set {
                this["OUTPUT_ALIGN_LAMI_Y_ABS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W510E")]
        public string OUTPUT_ALIGN_LAMI_T_ABS {
            get {
                return ((string)(this["OUTPUT_ALIGN_LAMI_T_ABS"]));
            }
            set {
                this["OUTPUT_ALIGN_LAMI_T_ABS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W5110")]
        public string OUTPUT_ALIGN_SUPPLY_X_INC {
            get {
                return ((string)(this["OUTPUT_ALIGN_SUPPLY_X_INC"]));
            }
            set {
                this["OUTPUT_ALIGN_SUPPLY_X_INC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W5112")]
        public string OUTPUT_ALIGN_SUPPLY_Y_INC {
            get {
                return ((string)(this["OUTPUT_ALIGN_SUPPLY_Y_INC"]));
            }
            set {
                this["OUTPUT_ALIGN_SUPPLY_Y_INC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W5114")]
        public string OUTPUT_ALIGN_SUPPLY_T_INC {
            get {
                return ((string)(this["OUTPUT_ALIGN_SUPPLY_T_INC"]));
            }
            set {
                this["OUTPUT_ALIGN_SUPPLY_T_INC"] = value;
            }
        }
    }
}
