//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligentFactory._0._UI._0__MENU {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _00__FormMenu_MainFrame_Backup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _00__FormMenu_MainFrame_Backup() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntelligentFactory._0._UI._0__MENU.00. FormMenu_MainFrame_Backup", typeof(_00__FormMenu_MainFrame_Backup).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {X=888,Y=22}과(와) 유사한 System.Drawing.Point 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Point timerAlarm_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("timerAlarm.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   {X=434,Y=17}과(와) 유사한 System.Drawing.Point 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Point timerAlarmWarning_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("timerAlarmWarning.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   {X=595,Y=17}과(와) 유사한 System.Drawing.Point 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Point timerConnection_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("timerConnection.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   {X=300,Y=17}과(와) 유사한 System.Drawing.Point 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Point timerDateTime_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("timerDateTime.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   {X=1002,Y=22}과(와) 유사한 System.Drawing.Point 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Point timerStatus_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("timerStatus.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
    }
}
